groups:
  - name: system-alerts
    rules:
      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% on {{ $labels.instance }}"

      # Disk space low
      - alert: DiskSpaceLow
        expr: (1 - (node_filesystem_free_bytes / node_filesystem_size_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "Disk space running low"
          description: "Disk usage is above 85% on {{ $labels.instance }} mount {{ $labels.mountpoint }}"

  - name: application-alerts
    rules:
      # Application down
      - alert: ApplicationDown
        expr: up{job="n8n-mcp-api"} == 0
        for: 1m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "N8N MCP API is down"
          description: "The N8N MCP API has been down for more than 1 minute"

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="n8n-mcp-api"}[5m])) > 1
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High API response time"
          description: "95th percentile response time is above 1 second for {{ $labels.method }} {{ $labels.route }}"

      # High error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{job="n8n-mcp-api",status_code=~"5.."}[5m]) / rate(http_requests_total{job="n8n-mcp-api"}[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for the last 5 minutes"

      # Database connection issues
      - alert: DatabaseConnectionHigh
        expr: pg_stat_activity_count > 80
        for: 5m
        labels:
          severity: warning
          team: database
        annotations:
          summary: "High number of database connections"
          description: "PostgreSQL has {{ $value }} active connections"

      # Redis connection issues
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
          team: infrastructure
        annotations:
          summary: "Redis is down"
          description: "Redis server is not responding"

  - name: business-alerts
    rules:
      # High cost per request
      - alert: HighCostPerRequest
        expr: increase(api_cost_total[1h]) / increase(api_requests_total[1h]) > 0.10
        for: 30m
        labels:
          severity: warning
          team: business
        annotations:
          summary: "High cost per API request"
          description: "Average cost per request is above $0.10 for the last hour"

      # Usage limit approaching
      - alert: UsageLimitApproaching
        expr: (api_usage_current / api_usage_limit) > 0.85
        for: 15m
        labels:
          severity: warning
          team: business
        annotations:
          summary: "Usage limit approaching"
          description: "User {{ $labels.user_id }} is at {{ $value | humanizePercentage }} of their usage limit"

      # Failed credential validations
      - alert: HighCredentialFailures
        expr: rate(credential_validation_failures_total[15m]) > 0.1
        for: 10m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High credential validation failures"
          description: "Credential validation failure rate is above 10% for the last 15 minutes"