# Jaeger all-in-one configuration for n8n-MCP
# This configuration is for development/small deployments
# For production, use separate collector, query, and storage components

# Collector configuration
collector:
  zipkin:
    host-port: :9411
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  queue:
    enabled: true
    queue-size: 5000
    num-workers: 50
  sampling:
    strategies-file: /etc/jaeger/sampling-strategies.json
    strategies-reload-interval: 10s

# Processor configuration
processor:
  jaeger-binary:
    server-host-port: :6832
    server-max-packet-size: 65000
    server-socket-buffer-size: 0
  jaeger-compact:
    server-host-port: :6831
    server-max-packet-size: 65000
    server-socket-buffer-size: 0

# Query service configuration
query:
  host-port: :16686
  base-path: /jaeger
  ui-config: /etc/jaeger/ui-config.json
  max-clock-skew-adjustment: 1s
  static-files: /usr/share/jaeger/ui

# Storage configuration
span-storage:
  type: elasticsearch
  elasticsearch:
    server-urls: http://elasticsearch:9200
    username: ${ES_USERNAME:elastic}
    password: ${ES_PASSWORD:changeme}
    index-prefix: jaeger
    date-layout: "2006-01-02"
    num-shards: 5
    num-replicas: 1
    timeout: 5s
    bulk:
      size: 5000000
      workers: 4
      flush-interval: 200ms
    version: 7
    log-level: error
    tags-as-fields:
      all: false
      config-file: /etc/jaeger/es-tags-as-fields.txt
    use-aliases: true
    create-index-templates: true
    use-ilm: true

# Dependencies storage
dependencies-storage:
  type: elasticsearch
  elasticsearch:
    server-urls: http://elasticsearch:9200
    username: ${ES_USERNAME:elastic}
    password: ${ES_PASSWORD:changeme}
    index-prefix: jaeger-dependencies
    date-layout: "2006-01-02"
    timeout: 5s

# Agent configuration (if using separate agent)
agent:
  reporter:
    grpc:
      host-port: jaeger-collector:14250
      retry:
        max: 3
        initial-interval: 100ms
        max-interval: 1s
        multiplier: 2
    type: grpc
    log-spans: false
  processor:
    jaeger-compact:
      server-host-port: :6831
    jaeger-binary:
      server-host-port: :6832
  http-server:
    host-port: :5778
  sampling:
    sampling-server-url: http://jaeger-collector:5778/sampling
    initial-sampling-rate: 0.001
    sampling-refresh-interval: 10s
    max-operations: 200

# Admin server configuration
admin-http-host-port: :14269

# Metrics configuration
metrics-backend: prometheus
metrics-http-route: /metrics

# Log level
log-level: info